### ISSUE TITLE
Group aministration page doesn't populate members/admins

### ISSUE THREAD

**Issue by soichih** [brainlife/brainlife#118]
![image](https://user-images.githubusercontent.com/923896/128412665-6632a24d-b4d5-4921-8c0d-0fcd95dd45fe.png)

Also.. for Users list, I am seeing this error message.

```
[Vue warn]: Invalid prop: type check failed for prop "value". Expected Number, String, got Array 

found in

---> <BFormInput>
       <BFormGroup>
         <Settings> at src/settings.vue
           <Warehouse> at src/warehouse.vue
             <Root>
```

I am not sure if it's related to users/groups.. but FYI.

Another thing.. Can we decrease the number of items to show per page? I think the list is too long at the moment.

**Comment by bhatiadheeraj** [comment]
https://github.com/brainlife/auth/blob/master/api/controllers/root.js#L274 

Please update it to 

`groups = await db.mongo.Group.find(find)
            .lean().populate('admins members', 'email fullname username sub');`

**Comment by soichih** [comment]
I've added "sub" to a few populate sub-fields. It seems to work now! Thanks!

Can you do the following still, though?

> Also.. for Users list, I am seeing this error message.
> Can we decrease the number of items to show per page?

**Comment by soichih** [comment]
@bhatiadheeraj The issue of updated members/admins list not updating the previously loaded list of groups is still an issue. I was able to reproduce this on production. I recommend updating submitGroup to apply the new group on the specific group in `this.group` instead of entirely reloading it.

Also, I think we should move Users and Groups tab to administrative page (not settings). Can you move them? We should probably create separate components for Users and Groups (<AdminUsers> / <AdminGroups>) and refactor other Admin tag components to individual components.

**Comment by bhatiadheeraj** [comment]
do you mean to create separate components for user edit and groupEdit or just to display users or groups?  https://github.com/brainlife/warehouse/pull/283/commits/3d9620d72d16cf2a12fd3786d37821989c1b1f4e

**Comment by soichih** [comment]
Fixed
