### ISSUE TITLE
Rule disappears after being newly created at page refresh 

### ISSUE THREAD

**Issue by francopestilli** [brainlife/brainlife#171]
OSX Monterey 12.1
Chrome V 100.0.4896.127

See video here:
https://youtu.be/INBz4V_aBtY

**Comment by soichih** [comment]
Looks like this is caused by project members not having access to project API to update the rule ordering. I will need to create a dedicated API to update the pipeline ordering under rule API which is accessible to both admin and members.

**Comment by soichih** [comment]
@sandrahanekamp mentions that this is fixed! :)
