### ISSUE TITLE
Skip landing page if logged in

### ISSUE THREAD

**Issue by adelavega** [brainlife/brainlife#177]
Small request, but I noticed that when you're logged in you still hit that introductory landing page, rather than being taken straight to your projects/dashboard.

I find this inconsistent w/ how most websites work (i.e. GitHub) that the landing page is really just to grab the attention of first time users.

**Comment by soichih** [comment]
@adelavega By "introductory landing page", do you mean the brainlife's main landing page? i.e. https://brainlife.io ? So, are you suggesting that, if user is logged in and when they visit https://brainlife.io, they should go straight to https://brainlife.io/projects?

**Comment by adelavega** [comment]
Yes. It just feels a bit divorced from the main app, and I get confused when I land on it. 

Especially because the Play button is used for "Sign Up" but when I scroll down the play button (top right) actually takes you to projects.

So I always accidentally click "Sign Up" when I'm already logged in.

**Comment by soichih** [comment]
I see, I understand now. I will discuss with the team and see if we should do the redirect.

I agree that those buttons on the landing page are a bit confusing. I am working on a redesigned version of home page now with a single "Login" button.

**Comment by adelavega** [comment]
Cool. I think at the minimum that would help, especially if it detects you are logged in and it looks different.
 
I was working on a landing page redesign myself today so just an observation.

**Comment by soichih** [comment]
The new landing page has been released and it redirects users to /projects page if they are logged in. If not, it redirects to /about which is our "landing" page - as suggested by @yarikoptic
