### ISSUE TITLE
Pull down https://brainlife.github.io/

### ISSUE THREAD

**Issue by francopestilli** [brainlife/brainlife#218]
Hi @anibalsolon I think we have this legacy website that needs to be put down:
https://brainlife.github.io/

The website also hosts https://brainlife.github.io/pestillilab, which also should go down, it is the first hit when looking for "pestilli lab" so we miss traffic at pestillilab.github.io because of that

**Comment by francopestilli** [comment]
@anibalsolon

**Comment by anibalsolon** [comment]
https://brainlife.github.io/ now redirects to https://brainlife.io
https://brainlife.github.io/plab now redirects to https://pestillilab.github.io/
