### ISSUE TITLE
Admin : Username, email, and fullname edit box disappears when input is deleted [Warehouse]

### ISSUE THREAD

**Issue by bhatiadheeraj** [brainlife/brainlife#223]
Currently, the user edit form uses v-if instead of v-model for the username, email, and fullname input boxes. This causes the entire input box to disappear when the user deletes all of the input in the box with the backspace key. Instead, the input box should remain visible with a placeholder value, allowing the user to continue editing the field. This behavior can be confusing and frustrating for users who accidentally delete the entire value and are unable to continue editing the field.
 
 
![image](https://user-images.githubusercontent.com/16397223/232178396-1110da12-59fd-4642-bdc7-f82f5d31fb34.png)

**Comment by nicoalee** [comment]
resolved
