### ISSUE TITLE
Profile Listing

### ISSUE THREAD

**Issue by stevengeeky** [brainlife/brainlife#32]
Soichi and I discussed the idea of having a dedicated page for profile listing
Such a page would contain:
* The list of users (icon, name, maybe an edit button if it's your own profile)
* (Eventually) the ability to click on a user and see their own profile as a dedicated page
* We could also merge or modify the settings page from auth and add user-personalized settings (like whether or not to display project icons, general UI settings, etc.)

Right now we don't really have a place to put it (similar to the datatypes page) but it's an idea for later
Creating it would also give us incentive to design a type of infinite scrolling that works for pages that are populated with cards (to support a large number of users or applications)

**Comment by soichih** [comment]
@bhatiadheeraj might want to implement the "list of users" page?
