### ISSUE TITLE
Allow user to edit dataset's datatype tag

### ISSUE THREAD

**Issue by soichih** [brainlife/brainlife#38]
We currently only allow users to edit dataset tag. I've seen a few instances of datatype tag incorrectly set and needing to be reset. I think we should allow user to edit this - as long as it's not exposed too openly.

One thing to note about editing datatype/tags is that, it could damage the dataset provenance.

**Comment by DanNBullock** [comment]
Maybe featuring a large popup warning indicating the purpose of the datatype tag and the potential consequences of doing this.  Might be an annoyance to some, but could prevent users from becoming their own worst enemy.

**Comment by soichih** [comment]
The button is somewhat hidden, but data object modal allows user to edit the datatype tag.

![image](https://user-images.githubusercontent.com/923896/144060522-b269a648-fd00-42ae-b222-362af0a00594.png)
