### ISSUE TITLE
Setup brainlife input files in BIDS structure at runtime

### ISSUE THREAD

**Issue by soichih** [brainlife/brainlife#43]
Brainlife could organize input files in BIDS (for BIDS compatible datatypes) to make it easier to run BIDS Apps on brainlife. This would've made @faskowit 's life much easier for app-fmriprep, for example. I believe there will be more and more BIDS apps in the future, so I think we should implement this soon.

**Comment by faskowit** [comment]
ya ya ya ya YAAAAAA, a BL ===>>> BIDS tool would be fantastic!  Would it be some sort of like meta-app?  Like, a brainlife App that needed BIDS folder would first git clone this tool?  In this way, it's never really an app on the BL interface, but is called by any App that needs this structure.  In my mind, this would flow with how things are setup as of now

**Comment by soichih** [comment]
@faskowit Yes, it shouldn't be an App in BL. I am thinking about making it part of our execution hook(https://github.com/brainlife/abcd-spec/tree/master/hooks) probably as a python script(?) and make it run automatically for all Apps when they are started. I think it can just look for `config._inputs` structure and setup a directory full of symlinks (in BIDS structure) based on the datatypes and output `meta` as BIDS sidecar.json.

 Would you like to collaborate on this?

**Comment by faskowit** [comment]
Ya ya fa sho I can help out with it -- not sure how the abcd-spec works
tho, so maybe I could help more on the BIDS end of things?

**Comment by soichih** [comment]
I will get started working on this. My initial use case for this feature is to run C-PAC BIDS App on brainlife. I will also work on `main` script for C-PAC and send a PR to C-PAC (@anibalsolon @ccraddock)

**Comment by soichih** [comment]
@faskowit I wrote a script called `bl2bids` and made it part of abcd hook. 
> https://github.com/brainlife/abcd-spec/blob/master/hooks/bl2bids

You can run it anywhere that has `config.json` in the current directory. It reads the `_inputs[]` in config.json and generates `bids` directory containing symlinks to the input files as specified by `config.json`

I might run this script automatically for all jobs, or we might want to let each App manually invoke `bl2bids` if it needs it (to run BIDS Apps, for example). I am not sure yet.

`bl2bids` doesn't really do much other than just setting up symlinks and create various .json for sidecars. It doesn't do any of the sidecar manipulation you were doing for fmriprep (for PhaseEncodingDirection?) Can you take a look? We need to add the capability to generate `dataset_description.json` and maybe handle other datatypes - like fieldmap, etc..

**Comment by faskowit** [comment]
ya ya ok a couple of things to add more control....  

* I think it might be good to insert a "fake" subject name like before, this way we can avoid errors with data where the subject name has a space or special character in it.  This happened before with user-uploaded data... seems like it can just be avoided with string like "SSSUB" like before. 
* ya, also I think the dataset description can similarly be fake, like we did before: https://github.com/brainlife/app-fmriprep/blob/9d4aada673b5adee5b02be0c490e98d3e7a1f5e7/main#L121
* I'm in favor of both of these "fake" steps because ultimately, they are for the benefit of the developers... while the user never sees this anyways

**Comment by soichih** [comment]
Thanks @faskowit 

To handle the case where subject / session name might contain invalid characters, I think we should add checks in bl2bids to either strip those invalid chars, or display some warning messages? I think we should keep the original subject / session name because users might be feeding multiple inputs from different subject/sessions so we probably want to preserve that information? 

I've added the fake dataset_description.json

**Comment by faskowit** [comment]
ahh, but I thought different subject / session organization would be handled by brainlife.  I don't imagine a scenario where people have to input multiple sessions, let's say run-1 and run-2, to the fmriprep app. Furthermore, I don't believe this aligns with the current way apps are setup... since this would be creating scenarios with variable numbers of inputs/outputs.  Instead, run-1 and run-2 will just be processed by running the fmriprep app two different times.  In this second scenario, the realistic BIDS did would not matter in my opinion

**Comment by faskowit** [comment]
for sure it's worth a shot to see how it does for now... the one thing that I know will not work is spaces in the name, so for sure string have to be cleaned in that regard.   I guess the next step would be to run it and the uses the bids-validator (https://github.com/bids-standard/bids-validator) to see if it produces a valid directory structure.

**Comment by soichih** [comment]
I've run bids-validator on bl2bids output, and the output looks ok. It's complaining a few missing `IntendedFor` bold image, but some of the files are expected to not be there - as we are only staging files that user specify (not all data from the original dataset). We could clean up missing files.. but I think most BIDS App should work fine with extra files listed?

I've worked on app-fmriprep. Basically removed most of the BIDS structure code out of `main`. I am seeing error message from `legacymultiproc.py`.. I am not sure what it means, but I think this is unrelated to the BIDS input structure.

```
Node: fmriprep_wf.single_subject_1_wf.summary
Working directory: /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/summary

Node inputs:

bold = ['/mnt/scratch/hayashis/syncthing/git/app-fmriprep/bids/sub-1/ses-1/func/sub-1_ses-1_run-1_task-rest_bold.nii.gz']
nstd_spaces = ['fsnative']
std_spaces = ['MNI152NLin2009cAsym']
subject_id = 1
subjects_dir = /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripout/freesurfer
t1w = ['/mnt/scratch/hayashis/syncthing/git/app-fmriprep/bids/sub-1/ses-1/anat/sub-1_ses-1_run-1_T1w.nii.gz']
t2w = ['/mnt/scratch/hayashis/syncthing/git/app-fmriprep/bids/sub-1/ses-1/anat/sub-1_ses-1_run-1_T2w.nii.gz']

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 432, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 100, in _run_interface
    return super(SubjectSummary, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 64, in _run_interface
    segment = self._generate_segment()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 124, in _generate_segment
    for series in bold_series)
  File "/usr/local/miniconda/lib/python3.7/collections/__init__.py", line 566, in __init__
    self.update(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.7/collections/__init__.py", line 653, in update
    _count_elements(self, iterable)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 124, in <genexpr>
    for series in bold_series)
TypeError: 'NoneType' object is not subscriptable

```

I will try to run the latest fmriprep (20.1.1) and see if I still run into this.

**Comment by soichih** [comment]
@faskowit I am running into the same issue with 20.1.1. I've opened an issue ticket for fmriprep > https://github.com/poldracklab/fmriprep/issues/2222

Meanwhile, do you see anything that I might be doing wrong? Does the bids input directory look ok, for example?

```
bids/
├── dataset_description.json
├── derivatives
│   └── 5e00405dcc6723f5c2bd18e7
│       └── sub-1
│           └── ses-1
│               └── dt-58cb22c8e13a50849b25882e.todo
│                   ├── sub-1_ses-1_run-1_freesurfer.json
│                   └── sub-1_ses-1_run-1_output -> ../../../../../../testdata/freesurfer/output
└── sub-1
    └── ses-1
        ├── anat
        │   ├── sub-1_ses-1_run-1_T1w.json
        │   ├── sub-1_ses-1_run-1_T1w.nii.gz -> ../../../../testdata/t1/t1.nii.gz
        │   ├── sub-1_ses-1_run-1_T2w.json
        │   └── sub-1_ses-1_run-1_T2w.nii.gz -> ../../../../testdata/t2/t2.nii.gz
        ├── fmap
        │   ├── sub-1_ses-1_run-1_magnitude1.nii.gz -> ../../../../testdata/fmap/magnitude1.nii.gz
        │   ├── sub-1_ses-1_run-1_magnitude2.nii.gz -> ../../../../testdata/fmap/magnitude2.nii.gz
        │   ├── sub-1_ses-1_run-1_phase1.json -> ../../../../testdata/fmap/phase1.json
        │   ├── sub-1_ses-1_run-1_phase1.nii.gz -> ../../../../testdata/fmap/phase1.nii.gz
        │   ├── sub-1_ses-1_run-1_phase2.json -> ../../../../testdata/fmap/phase2.json
        │   └── sub-1_ses-1_run-1_phase2.nii.gz -> ../../../../testdata/fmap/phase2.nii.gz
        └── func
            ├── sub-1_ses-1_run-1_task-rest_bold.json
            └── sub-1_ses-1_run-1_task-rest_bold.nii.gz -> ../../../../testdata/bold/bold.nii.gz
```

I've pushed a `bids` branch > https://github.com/brainlife/app-fmriprep/blob/bids/main If you could test it with your data.. that would be awesome.

**Comment by faskowit** [comment]
Ahhh hmmm and it passes the bids validator check, ya?

Also, did you say you were setting this structure up with symbolic links?
Did you try hard links?  I do remember trying to use a symbolic link
structure one time and it didn't work... despite the bids being seemingly
correct.  I switched over to hard links and it worked... could be worth a
shot?

**Comment by soichih** [comment]
I just ran bids-validator again and it revealed that the way I was setting up bold.nii.gz was wrong.. Thank you for suggesting it. I've corrected the problem and now the workflow is running past the point it was erroring out previously.

Thanks for the tip on symlinks. I am still using symlinks, but so far the workflow seems to be working ok. I will let you know how it goes.

**Comment by faskowit** [comment]
ahhh cool cool!  interested to know the problem with the bold; was it the ordering of the elements in the name?

**Comment by faskowit** [comment]
also, the previous symlink vs hard link thing happened when I was toy'ing around with it in docker... so also could have been a docker thing and getting the mounting wrong at the time.

**Comment by soichih** [comment]
bl2bids can now handle field map (to a certain degree) and we will be making more updates in the near future. I will close this ticket for now as the original goal has been accomplished.
