### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/mnt/osiris' on archiving processed files

### ISSUE THREAD

**Issue by amnsbr** [brainlife/brainlife#66]
Hi,

I have uploaded one of my participants with BIDS format and using the CLI to test my pipeline. Freesurfer was the first step that was completed and validated successfully, but I am unable to archive the outputs, getting this error: "OSError: [Errno 13] Permission denied: '/mnt/osiris'". And this is the content of the error.log file:
```
Traceback (most recent call last):
  File "./main", line 30, in <module>
    os.makedirs(dest)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/mnt/osiris'
```
I also tested other apps, and another subject (brainlife's BC) and got the same error. Waiting and retrying after ~10 hrs also did not help. I'm not sure if I'm doing something wrong or if this is a bug. Can you please help me with this problem? Many thanks in advance.

**Comment by soichih** [comment]
@amnsbr I had yet another configuration issue and I believe I've corrected it. I am rerunning all failed archived jobs now, so your data should be archived in your project shortly. Could you check?

**Comment by amnsbr** [comment]
@soichih It was not automatically archived (yet), but I did it manually and it worked. Thank you very much.
