### ISSUE TITLE
Uploading Image to create an organization landing page 

### ISSUE THREAD

**Issue by francopestilli** [brainlife/brainlife#67]
<img width="1220" alt="brainlife_github" src="https://user-images.githubusercontent.com/2119795/93723350-7fa3d980-fb63-11ea-9272-e9fb133356a4.png">

**Comment by soichih** [comment]
@francopestilli Are you trying to host an image on github so you can link it from the brainlife/brainlife repo README?

If so, you can add the image in this directory
> https://github.com/brainlife/brainlife/tree/master/images
And you can reference it via the "raw" github URL.

**Comment by francopestilli** [comment]
@soichih we can delete this. It turns out we cannot make a readme file for an organization. This is allowed only for individual users.
