### ISSUE TITLE
The Open Graph metadata & HTML preview do not update with updates to an app's metadata

### ISSUE THREAD

**Issue by shnizzedy** [brainlife/brainlife#69]
For example, [![brainlife.io/app](https://img.shields.io/badge/brainlife.io-app.399-green.svg)](https://brainlife.io/app/5f3593e84615e04651bf9364) has the following name:

```text
C-PAC
```

but the name-at-creation appears in the Open Graph metadata
```XML
<meta name="og:title" content="C-PAC (testing)"/>
```

and the HTML preview

```HTML
<h1>C-PAC (testing)</h1>
```

---

Relatedly, leaving the description blank populates from the GitHub description on the page, but renders `null` in the Open Graph metadata

```XML
<meta name="og:description" content="null"/>
```

and HTML preview

```HTML
<p>null</p>
```

**Comment by soichih** [comment]
The metadata updater was broken, so I've fixed it. It should get updated at least once a day now. I will add a check on our monitoring service.
