### ISSUE TITLE
Feature request:  Search for projects/datasets containing [datatype]

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/brainlife#76]
Currently, the dataset search functionality (https://brainlife.io/datasets) has a limited number of data types that can be searched for.  Additionally, there is no way to search in this fashion (by datatype presence) within projects (https://brainlife.io/projects).  I could be wrong about this though, and there may be some sort of specific/special search command/string that does this.

Regardless, it would be very helpful to be able to find datasets/projects which contain the relevant datatype that someone is interested in.  For example, if I wanted to look at projects with parcellations.

**Comment by soichih** [comment]
> Currently, the dataset search functionality (https://brainlife.io/datasets) has a limited number of data types that can be searched for.
We only allow searching for datatype that exists on both BIDS and Brainlife supported BIDS datatype. Those listed in /datasets page are currently the only such datatypes.

> Additionally, there is no way to search in this fashion (by datatype presence) within projects (https://brainlife.io/projects).
We currently don't allow searching project via datatype name. I will add that capability.

**Comment by DanNBullock** [comment]
>  We only allow searching for datatype that exists on both BIDS and Brainlife supported BIDS datatype. Those listed in /datasets page are currently the only such datatypes.

That's probably fine given that there aren't datatypes there in the datalad datasets that aren't already in bids (usually)

>  We currently don't allow searching project via datatype name. I will add that capability.

Cool cool, thanks

**Comment by soichih** [comment]
This has been implemented.
