### ISSUE TITLE
Query funding information / add links

### ISSUE THREAD

**Issue by soichih** [brainlife/brainlife#94]
Under our publication page, we show list of funding sources like this

![image](https://user-images.githubusercontent.com/923896/117689581-e411b880-b187-11eb-9281-3cb0022c559e.png)

We should make these indicator links so user can click on it and take them to the NIH / NSF page.

For example, the first entry "NSF IIS-1636893" can be linked to
> https://www.nsf.gov/awardsearch/showAward?AWD_ID=1636893

**Comment by bhatiadheeraj** [comment]
@soichih what is the URL format for NIH-based entries?
